title: Data Analyst # your name (or website title) here
logo: "/images/logo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  I’m your personal Data Analyst built on top of Llama-3.1-70B and the ReAct agent framework. I break down your task step-by-step until I reach an answer/solution. Along the way I share my thoughts, actions (Python code blobs), and observations. I come packed with pandas, numpy, sklearn, matplotlib, seaborn, and more!
  <br><br>
  <a href="https://huggingface.co/spaces/dkondic/data-analyst">Try me on Hugging Face!</a>

theme: jekyll-theme-minimal
#google_analytics: UA-000000-0 # your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'
